### ISSUE TITLE
[User feedback] OrgUnit select disappears

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#10]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

Hello, 
I see that when I scroll down the selector of OrgUnit by level or groups stays up and hence disappears from the screen, could we make it come down as we scroll?

Thanks!

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1591305341589287182.png )

**Comment by adrianq** [comment]
Solved in 3.4.0.  OU Group and Level filters displayed at the top all the time even if the user scrolls down in the OU Tree selector
