### ISSUE TITLE
[User feedback] The form has the orgUnits even when it shouldn't?

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#11]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
- Platform: MacIntel

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

When the tick box for select orgUnits is unticked, the downloaded form seems to show all orgUnits to which the program is assigned.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1591307241470315264.png )

**Comment by adrianq** [comment]
Fixed in 3.4.0. We add no org unit to the validation if the box is unchecked
