### ISSUE TITLE
[User feedback] The template has orgUnits when select orgUnits on template import is selected

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#12]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
- Platform: MacIntel

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

I though that when we say that orgUnits should be show during import, we could generate a template with orgUnits.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1591307452603989745.png )

**Comment by ifoche** [comment]
By default checkbox "select available OUs" must be checked

**Comment by adrianq** [comment]
Solved in 3.4.0
