### ISSUE TITLE
[User feedback] The number of data values differ from the one that was announced

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#14]
## dhis2

Username: ignacio.foche

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-demo/api/apps/Bulk-Load/index.html#/import

The number of data values differ from the one that was announced

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1591696165870379121.png )

**Comment by adrianq** [comment]
We are just parsing the answer from the endpoint which is also considering as an imported DE the date. Closing it now as it is more a DHIS2 bug than an app bug
