### ISSUE TITLE
[User feedback] Incorrect summary stats (Update, deleted) and not deletion of empty cells

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#16]
## dhis2

Username: ryan

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
- Platform: MacIntel

## User report
URL: http://localhost:8080/dhis/api/apps/Bulk-Load/index.html#/import

I have one row of data in the template. I has correctly found 3 values out of 69 columns, the others are empty. 
There is data in the system corresponding to the cells that are empty in the template, so I think those cells should be deleted. If so, it should say 66 to be deleted. No data is actually deleted, don;t know if there is a parameter which allows for this to happen.

Changed values are updated, but re not reflected in the summary count.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1592396989870512493.png )

**Comment by adrianq** [comment]
Delete feature has been fixed in 3.6.0
