### ISSUE TITLE
[User feedback] Add translations in french

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#17]
## dhis2

Username: test_mal

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
- Platform: MacIntel

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

Part of the application appears in french, but not all. Could we add translations for the headings and labels that are missing translations?  French and spanish.
Thanks!

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1592434802718193632.png )

**Comment by adrianq** [comment]
Fixed in 3.5.0
