### ISSUE TITLE
[User feedback] Translate in French

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#18]
## dhis2

Username: test_mal

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

We need to translate the application in french and Spanish. How much time will it take? And how much time will it take to add Portuguese as well?

I have provide the translations of all sentences in all three languages.

Bests! 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-159282121824087470.png )

**Comment by adrianq** [comment]
Fixed in 3.5.0
