### ISSUE TITLE
[User feedback] user has not acess to the templates

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#20]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/Bulk-Load/index.html#/settings

USer gets no rights to access the template and the settings sections through its userGroup.
lea.knopf. Its userGroup is NTD_NZD_admin.
She's only getting the rights when selecting the user directly.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596637942271130053.png )

**Comment by SferaDev** [comment]
Couldn't replicate with lea's user on a docker copy of DEV

**Comment by adrianq** [comment]
Closing this as we cannot replicate it and it doesn't seem to be an issue anymore
