### ISSUE TITLE
[User feedback] Error loading templates with my user

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#21]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/Bulk-Load/index.html#/import

I have exported a template (ADMIN_Analytics_Check(Event)) with populated data, and when I try to load the file the app never load it.
(I have verified that the excel file has data.)
user: idelcano

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1597401146478191901.png )

**Comment by adrianq** [comment]
This is an already known bug. The template needs to be saved/modified in order to be used to import  data into the system
