### ISSUE TITLE
[User feedback] Can't select organization unit

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#22]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/Bulk-Load/index.html#/import

Hi guys, I am trying to upload data into a orgUnit, but on the screen  I can't select the OrgUnit...
Maybe this is not the step where the orgUnit should appear?
Could you have a look?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1598262390861189844.png )

**Comment by adrianq** [comment]
This error seems to be fixed in 3.6.0
