### ISSUE TITLE
[User feedback] Import file process can not process

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#23]
## dhis2

Username: nmcpirn

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/import

there are error 404

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1599253266922374379.png )

**Comment by adrianq** [comment]
Lastest version of the app and the template seem to be working fine
