### ISSUE TITLE
[User feedback] Bug in Import Data

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#25]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-ento-vc/api/apps/Bulk-Load/index.html#/import

Help Help Help!

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601559038350163559.png )

**Comment by adrianq** [comment]
Dummy issue. Closing now!
