### ISSUE TITLE
[User feedback] No detecta duplicados

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#26]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
- Platform: MacIntel

## User report
URL: http://127.0.0.1:8080/api/apps/Bulk-Load/index.html#/import

Importo dos veces el mismo archivo y no detecta duplicados. Para que pase hay que activar el check de seleccionar a mano la Organization unit. 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1602239771952417716.png )

**Comment by adrianq** [comment]
Fixed in 3.10.1
