### ISSUE TITLE
[User feedback] Stuck on Checking Duplicates step

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#27]
## dhis2

Username: sysadmin

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
- Platform: Win32

## User report
URL: https://tland.hispmoz.org/namb/api/apps/Bulk-Load/index.html#/import

I have set 3 data elements to be used for duplicate detection of an event program with ~230 data elements total

I was able to successfully download a template for a single org unit + category option combo and filled out about ~10 data elements

Upon trying to import its just stuck on the Checking Duplicates page

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1603145140697246759.png )

**Comment by adrianq** [comment]
Unable to track back.
