### ISSUE TITLE
[User feedback] Scrollbar not working ok

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#28]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8084/api/apps/Bulk-Load/index.html#/download

The scrollbar is shown on the right over another component and it doesn't work, I can move up and down it with the central button of the mouse but not directly dragging the scrollbar.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1603724653136337980.png )

**Comment by adrianq** [comment]
This org unit component will be refactored in the short term
