### ISSUE TITLE
[User feedback] Error while creating new TEI

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#29]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/Bulk-Load/index.html#/import

The TEI were created by downloading existing one, copying them an removing the UID

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1604446486820140103.png )

**Comment by adrianq** [comment]
Will be fixed in 3.7.0
