### ISSUE TITLE
[User feedback] Import failing to change BOOLEAN attribute

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#30]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-ento-vc/api/apps/Bulk-Load/index.html#/import

Other attributes are changed, but boolean one (parous?) is ignored

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1604526746335247280.png )

**Comment by ifoche** [comment]
Some important extra info:

![screenshots_1604526260_2244_04112020_1075x410](https://user-images.githubusercontent.com/10931645/98171809-a38f6480-1ef0-11eb-8e00-770c3b881482.png)


![screenshots_1604526585_2249_04112020_991x1028](https://user-images.githubusercontent.com/10931645/98171774-91adc180-1ef0-11eb-9eba-a6250ef7836e.png)

**Comment by adrianq** [comment]
Will be fixed in 3.7.0
