### ISSUE TITLE
[User feedback] Some data is imported but doesn't appear in DHIS2

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#31]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/Bulk-Load/index.html#/import

I have managed to import data from the Resistance Mechanism stage of the Mosquito tracker of discovery. When I download data, it appears on the excel template, however it does not appear in the system.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1604686751663769454.png )

**Comment by adrianq** [comment]
Close as this cannot be reproduced and seems to be a DHIS2 issue
