### ISSUE TITLE
[User feedback] No data downloaded from Bulk Load

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#33]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/Bulk-Load/index.html#/download

Hi guys,
I am trying to download data for the program IRS Campaigns and I get nothing in the form..while there is data for 2019.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1605257966737886125.png )

**Comment by adrianq** [comment]
We cannot reproduce this error. A possibility is that the events were introduced without a category option. We fetch the events per category option and, therefore, we will not be able to "see" those events
