### ISSUE TITLE
[User feedback] question about app functionalty in this version

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#36]
## dhis2

Username: adam704a

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh)
- Platform: MacIntel

## User report
URL: https://reachhealthdhis2.rti-ghd.org/api/apps/Bulk-Load/index.html#/download

does this app support completing the datasets

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1610574714401805882.png )

**Comment by adrianq** [comment]
Not at the moment but it is a feature we would like to include in the midterm once we find funding and/or time :)
