### ISSUE TITLE
[User feedback] 2020 is the last year that can be selected

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#38]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/Bulk-Load/index.html#/download

Could you please add 2021?
(Lucia)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1615384892808300488.png )

**Comment by adrianq** [comment]
All years are available by default. This issue cannot be reproduce
