### ISSUE TITLE
[User feedback] Export template

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#45]
## dhis2

Username: ryan

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
- Platform: MacIntel

## User report
URL: https://dhistvd.afro.who.int/dhis/api/apps/Bulk-Load/index.html#/download

v3.4.2 - Level 6 is not selectable, only up until level 5.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1620135964894655489.png )

**Comment by adrianq** [comment]
Selectable org units depend on the program or dataset, i.e. the organization units assigned to the dataset/program are the ones that can be selected by the user.
