### ISSUE TITLE
[User feedback] CostaRica_NHWA2020

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#57]
## dhis2

Username: v.leiva

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/import

NHWA 2020 Module 1

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1630271078890211955.png )

**Comment by SferaDev** [comment]
I will follow up tomorrow with Teena

**Comment by SferaDev** [comment]
On an internal mailing list I see the user has already reported the data correctly. Closing issue.
