### ISSUE TITLE
[User feedback] Text coming out of box in french

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#6]
## dhis2

Username: test_mal

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

Please see the screen capture.
Thanks!

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1591093168472923611.png )

**Comment by adrianq** [comment]
Closing this for now as it is not easy to solve and it doesn't have a big impact
