### ISSUE TITLE
[User feedback] Cannt read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#69]
## dhis2

Username: admin

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
- Platform: MacIntel

## User report
URL: https://dhis2.zccpkwatu.org/main/api/apps/Bulk-Load/index.html#/download

I keep getting this error when importing or download template with data.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1643621544998458971.png )

**Comment by SferaDev** [comment]
To be fixed in 3.17.0
