### ISSUE TITLE
[User feedback] Hide the choice of model from end-users

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#7]
## dhis2

Username: test_mal

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

End-users will only see a menu with data collection forms (programs and datasets they have access to) and Bulk Load should recognize if their selection is a program or a data set automatically.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1591097268321493016.png )

**Comment by adrianq** [comment]
Solved in 3.4.0 We have added the option 'All' that contains every program and dataset in a single dropdown sorted alphabetically
