### ISSUE TITLE
[User feedback] Transform program validation rules into data validations in excel

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#8]
## dhis2

Username: test_mal

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

When users download a template, the excel template should contain data validation rules that mimic the program validation rules in DHIS2.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1591097344587946663.png )

**Comment by ifoche** [comment]
**Most important**
1) Limit depending on the data element type the value that's inside the field
2) Auto-calc value depending on a PR expression

**Medium important**
3) Limit depending on a value from other DE

**Less important**
4) Show/hide option/values depending on other dataElement values

**Comment by ifoche** [comment]
DE types examples:
- percent are not percents
- negative numbers are not validated
- dates
- etc

**Comment by adrianq** [comment]
This has been moved to individual issues and some of the sub-tasks are out of scope
