### ISSUE TITLE
[User feedback] Cache problem?

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#9]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/download

After I selected the sentinel sites for a country, I clicked deselect and tried to select sentinel sites for another country and I can't,although I know the country has sites in WIDP...could it be a cache issue? 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1591305286444609470.png )

**Comment by adrianq** [comment]
This error seems to be fixed in the latest version
